sudo: false
language: python
python:
  # - 2.7
  # - 3.3
  # - 3.4
  # - 3.5
  - 3.6
  - 3.7-dev
  # - pypy  # https://github.com/travis-ci/travis-ci/issues/6865
  # - pypy3
  # - pypy2.7-5.8.0
  # - pypy3.5-5.8.0
install:
 - pip install -r requirements.txt codecov pytest-cov codacy-coverage responses
script:
 - py.test --verbose --cov-report term --cov-report xml --cov=psub tests
after_success:
 - codecov
 - python-codacy-coverage
notifications:
  email: oczkers@gmail.com
